### ISSUE TITLE
circular data structures when encoding

### ISSUE THREAD

**Issue by cloverstd** [json-iterator/go#199]
```golang
package main

import jsoniter "github.com/json-iterator/go"

var json = jsoniter.ConfigCompatibleWithStandardLibrary

func main() {

	a := &A{}
	a.B1 = &B{a}
	ping := &Ping{a}

	json.Marshal(ping)

}

type Ping struct {
	Pong *A
}

type A struct {
	B1 *B
}

type B struct {
	A1 *A
}
```

This code will panic with `runtime: goroutine stack exceeds 1000000000-byte limit`

Platform: `go version go1.9 darwin/amd64`

ref https://github.com/golang/go/issues/10769

**Comment by taowen** [comment]
jsoniter is compatible with encoding/json. If this is fixed in encoding/json, I will fix it as well.

Tracking recursion is possible in user extension, for example: https://github.com/v2pro/plz/blob/master/witch/exporter.go

The `Attachment` field in Stream and Iterator is added to support this kind of tracking

**Comment by MoZhonghua** [comment]
@taowen this has been fixed in encoding/json, see https://go-review.googlesource.com/c/go/+/187920

**Comment by machoxo** [comment]
It is still not supported.
