### ISSUE TITLE
ToVal causing panic: not implemented

### ISSUE THREAD

**Issue by cmoad** [json-iterator/go#246]
Trying to fetch a nested array and I don't understand why arrayLazyAny supports ToVal, but not arrayAny.

Here is a simple example that causes the issue:

```
var blocks []int
jsoniter.Get([]byte(`{"a":[{"b": 1},{"b",2}]}`), "a", '*', "b").ToVal(blocks)
```

**Comment by taowen** [comment]
combine '*' and ToVal is not supported, as it requires structure to structure binding, which is complicated. `jsoniter.Get` is designed to simplify simple task. would like to keep it simple, and instead of being more generic. binding data to not exact structure, with some transformation in the process is useful. But not that useful to worthwhile.

**Comment by cmoad** [comment]
Thanks for the explanation, @taowen. It's helpful to know the context.
